[build]
builder = "NIXPACKS"
buildCommand = "uv sync --frozen"

[deploy]
preDeployCommand = ["uv run python manage.py migrate"]
startCommand = "uv run gunicorn credit_mate_ai.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
