[build]
builder = "nixpacks"

[deploy]
startCommand = "uv run python manage.py migrate --noinput && uv run gunicorn credit_mate_ai.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --keep-alive 5 --log-file - --access-logfile - --error-logfile -"
healthcheckPath = "/health/"
healthcheckTimeout = 900
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for Railway deployment
[[deploy.environmentVariables]]
name = "DJANGO_SETTINGS_MODULE"
value = "credit_mate_ai.settings"

[[deploy.environmentVariables]]
name = "SECURE_SSL_REDIRECT"
value = "True"

[[deploy.environmentVariables]]
name = "SECURE_PROXY_SSL_HEADER"
value = "HTTP_X_FORWARDED_PROTO,https"

[[deploy.environmentVariables]]
name = "PORT"
value = "8000"

[[deploy.environmentVariables]]
name = "PYTHONUNBUFFERED"
value = "1"
