# Generated by Django 5.2.2 on 2025-06-09 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "interest_rate_apr",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("lounge_access_international", models.PositiveIntegerField(default=0)),
                ("lounge_access_domestic", models.PositiveIntegerField(default=0)),
                (
                    "cash_advance_fee",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "late_payment_fee",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("annual_fee_waiver_policy", models.JSONField(blank=True, null=True)),
                ("reward_points_policy", models.TextField(blank=True, default="")),
                ("additional_features", models.JSONField(blank=True, default=list)),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=512,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to="banks.bank",
                    ),
                ),
            ],
            options={
                "db_table": "credit_cards_creditcard",
                "ordering": ["bank__name", "name"],
                "unique_together": {("bank", "name")},
            },
        ),
    ]
