# Generated by Django 5.2.2 on 2025-06-09 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcard",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="creditcard",
            old_name="updated_at",
            new_name="modified",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="source_url",
        ),
    ]
