# Generated by Django 5.2.4 on 2025-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0002_rename_created_at_creditcard_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="lounge_access_domestic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="lounge_access_international",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
