# Generated by Django 5.2.4 on 2025-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0003_convert_lounge_access_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="lounge_access_condition",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
