# Generated by Django 5.2.5 on 2025-11-13 19:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0004_creditcard_lounge_access_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant & Dining"),
                            ("HEALTHCARE", "Healthcare & Hospital"),
                            ("SHOPPING", "Shopping & Retail"),
                            ("TRAVEL", "Travel & Transportation"),
                            ("FUEL", "Fuel & Gas Stations"),
                            ("ENTERTAINMENT", "Entertainment & Recreation"),
                            ("GROCERY", "Grocery & Supermarket"),
                            ("ONLINE", "Online Shopping"),
                            ("UTILITIES", "Utilities & Bills"),
                            ("EDUCATION", "Education & Learning"),
                            ("OTHER", "Other Benefits"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "mcc_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Merchant Category Codes (MCC) aligned with this category",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order for UI display"),
                ),
            ],
            options={
                "verbose_name": "Benefit Category",
                "verbose_name_plural": "Benefit Categories",
                "db_table": "credit_cards_benefit_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="creditcard",
            name="annual_fee_waiver_difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Easy to Waive"),
                    ("MODERATE", "Moderate Conditions"),
                    ("DIFFICULT", "Difficult to Waive"),
                    ("NOT_AVAILABLE", "No Waiver Available"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="AI-classified difficulty of waiving the annual fee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="best_for_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated use case tags (e.g., 'Cashback', 'Travel Miles')",
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="spending_tier",
            field=models.CharField(
                choices=[
                    ("ENTRY", "Entry Level"),
                    ("MID", "Mid-Range"),
                    ("PREMIUM", "Premium"),
                    ("ULTRA_PREMIUM", "Ultra Premium"),
                ],
                default="MID",
                help_text="Card tier classification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CreditCardBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reward rate percentage (e.g., 5.0 for 5% cashback)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reward_description",
                    models.TextField(
                        blank=True, help_text="Human-readable reward description"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Conditions or restrictions for this benefit",
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=100,
                        help_text="AI confidence score (0-100) for this classification",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a primary benefit of the card",
                    ),
                ),
                (
                    "benefit_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_benefits",
                        to="credit_cards.benefitcategory",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_benefits",
                        to="credit_cards.creditcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Card Benefit",
                "verbose_name_plural": "Credit Card Benefits",
                "db_table": "credit_cards_creditcard_benefit",
                "ordering": ["-is_primary", "-reward_rate", "benefit_category__name"],
                "unique_together": {("credit_card", "benefit_category")},
            },
        ),
        migrations.AddField(
            model_name="creditcard",
            name="benefit_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="credit_cards",
                through="credit_cards.CreditCardBenefit",
                to="credit_cards.benefitcategory",
            ),
        ),
    ]
