# Generated by Django 5.2.5 on 2025-11-18 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0010_add_sync_timestamps_to_crawled_content"),
        ("credit_cards", "0004_creditcard_lounge_access_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user_name",
                    models.CharField(
                        help_text="Name of the user providing the rating", max_length=100
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email of the user (not displayed publicly)",
                        max_length=254,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_verified_user",
                    models.BooleanField(
                        default=False, help_text="Whether user is verified cardholder"
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Card Rating",
                "verbose_name_plural": "Credit Card Ratings",
                "db_table": "credit_cards_rating",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CreditCardReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user_name",
                    models.CharField(
                        help_text="Name of the user writing the review", max_length=100
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email of the user (not displayed publicly)",
                        max_length=254,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Review title/headline", max_length=200),
                ),
                ("review_text", models.TextField(help_text="Detailed review content")),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Overall rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("pros", models.TextField(blank=True, help_text="Positive aspects")),
                ("cons", models.TextField(blank=True, help_text="Negative aspects")),
                (
                    "helpful_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of users who found this review helpful",
                    ),
                ),
                (
                    "usage_duration_months",
                    models.IntegerField(
                        blank=True,
                        help_text="How long user has been using the card (in months)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_verified_user",
                    models.BooleanField(
                        default=False, help_text="Whether user is verified cardholder"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Whether review is approved for display"
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Card Review",
                "verbose_name_plural": "Credit Card Reviews",
                "db_table": "credit_cards_review",
                "ordering": ["-helpful_count", "-created"],
            },
        ),
        migrations.AddField(
            model_name="creditcard",
            name="affiliate_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Affiliate tracking code or partner ID",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="annual_fee_waiver_difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Easy to Waive"),
                    ("MODERATE", "Moderate Conditions"),
                    ("DIFFICULT", "Difficult to Waive"),
                    ("NOT_AVAILABLE", "No Waiver Available"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="AI-classified difficulty of waiving the annual fee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="apply_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct application URL (may be affiliate link)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="best_for_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-generated use case tags (e.g., 'Cashback', 'Travel Miles')",
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="commission_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed commission amount in BDT per approved application",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated commission rate percentage (e.g., 5.00 for 5%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="spending_tier",
            field=models.CharField(
                choices=[
                    ("ENTRY", "Entry Level"),
                    ("MID", "Mid-Range"),
                    ("PREMIUM", "Premium"),
                    ("ULTRA_PREMIUM", "Ultra Premium"),
                ],
                default="MID",
                help_text="Card tier classification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BenefitCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant & Dining"),
                            ("HEALTHCARE", "Healthcare & Hospital"),
                            ("SHOPPING", "Shopping & Retail"),
                            ("TRAVEL", "Travel & Transportation"),
                            ("FUEL", "Fuel & Gas Stations"),
                            ("ENTERTAINMENT", "Entertainment & Recreation"),
                            ("GROCERY", "Grocery & Supermarket"),
                            ("ONLINE", "Online Shopping"),
                            ("UTILITIES", "Utilities & Bills"),
                            ("EDUCATION", "Education & Learning"),
                            ("OTHER", "Other Benefits"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "mcc_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Merchant Category Codes (MCC) aligned with this category",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order for UI display"),
                ),
            ],
            options={
                "verbose_name": "Benefit Category",
                "verbose_name_plural": "Benefit Categories",
                "db_table": "credit_cards_benefit_category",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="idx_category_active_order",
                    ),
                    models.Index(fields=["category_type"], name="idx_category_type"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditCardBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reward rate percentage (e.g., 5.0 for 5% cashback)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reward_description",
                    models.TextField(
                        blank=True, help_text="Human-readable reward description"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True,
                        help_text="Conditions or restrictions for this benefit",
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=100,
                        help_text="AI confidence score (0-100) for this classification",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a primary benefit of the card",
                    ),
                ),
                (
                    "benefit_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_benefits",
                        to="credit_cards.benefitcategory",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_benefits",
                        to="credit_cards.creditcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Card Benefit",
                "verbose_name_plural": "Credit Card Benefits",
                "db_table": "credit_cards_creditcard_benefit",
                "ordering": ["-is_primary", "-reward_rate", "benefit_category__name"],
            },
        ),
        migrations.AddField(
            model_name="creditcard",
            name="benefit_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="credit_cards",
                through="credit_cards.CreditCardBenefit",
                to="credit_cards.benefitcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["is_active", "annual_fee"], name="idx_card_active_fee"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["annual_fee_waiver_difficulty"], name="idx_card_waiver_diff"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(fields=["spending_tier"], name="idx_card_tier"),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(fields=["bank", "is_active"], name="idx_card_bank_active"),
        ),
        migrations.AddField(
            model_name="creditcardrating",
            name="credit_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="credit_cards.creditcard",
            ),
        ),
        migrations.AddField(
            model_name="creditcardreview",
            name="credit_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="credit_cards.creditcard",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardbenefit",
            index=models.Index(
                fields=["is_primary", "reward_rate"], name="idx_benefit_primary_rate"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardbenefit",
            index=models.Index(
                fields=["benefit_category", "is_primary"], name="idx_benefit_cat_primary"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="creditcardbenefit",
            unique_together={("credit_card", "benefit_category")},
        ),
        migrations.AddIndex(
            model_name="creditcardrating",
            index=models.Index(
                fields=["credit_card", "-created"], name="idx_rating_card_date"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardrating",
            index=models.Index(fields=["rating"], name="idx_rating_value"),
        ),
        migrations.AlterUniqueTogether(
            name="creditcardrating",
            unique_together={("credit_card", "user_email")},
        ),
        migrations.AddIndex(
            model_name="creditcardreview",
            index=models.Index(
                fields=["credit_card", "-helpful_count", "-created"],
                name="idx_review_card_helpful",
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardreview",
            index=models.Index(
                fields=["is_approved", "-created"], name="idx_review_approved"
            ),
        ),
    ]
