# Generated by Django 5.2.5 on 2025-11-13 19:20

from django.db import migrations


def create_benefit_categories(apps, schema_editor):
    """Create initial benefit categories with MCC code alignment.

    Based on ISO 18245 Merchant Category Codes (MCC) standard.
    """
    BenefitCategory = apps.get_model("credit_cards", "BenefitCategory")

    categories = [
        {
            "name": "Restaurant & Dining",
            "category_type": "RESTAURANT",
            "description": "Cashback and rewards on restaurant, cafe, and food delivery purchases",
            "mcc_codes": [5812, 5813, 5814],  # Restaurants, Bars, Fast Food
            "icon": "🍽️",
            "display_order": 1,
        },
        {
            "name": "Healthcare & Hospital",
            "category_type": "HEALTHCARE",
            "description": "Benefits on hospital bills, doctor visits, pharmacy, and medical expenses",
            "mcc_codes": [
                8011,  # Doctors, Physicians
                8021,  # Dentists, Orthodontists
                8062,  # Hospitals
                8099,  # Medical Services
                5912,  # Pharmacies
            ],
            "icon": "🏥",
            "display_order": 2,
        },
        {
            "name": "Shopping & Retail",
            "category_type": "SHOPPING",
            "description": "Rewards on shopping at retail stores, department stores, and boutiques",
            "mcc_codes": [
                5311,  # Department Stores
                5411,  # Grocery Stores
                5651,  # Family Clothing Stores
                5941,  # Sporting Goods
                5942,  # Book Stores
                5732,  # Electronics
            ],
            "icon": "🛍️",
            "display_order": 3,
        },
        {
            "name": "Travel & Transportation",
            "category_type": "TRAVEL",
            "description": "Benefits on airlines, hotels, travel agencies, and transportation",
            "mcc_codes": [
                3000,
                3001,
                3002,  # Airlines
                3501,
                3502,  # Hotels, Resorts
                4111,  # Transportation - Commuter Transport
                4121,  # Taxis, Limousines
                4722,  # Travel Agencies
            ],
            "icon": "✈️",
            "display_order": 4,
        },
        {
            "name": "Fuel & Gas Stations",
            "category_type": "FUEL",
            "description": "Cashback on fuel, gas stations, and electric vehicle charging",
            "mcc_codes": [
                5541,  # Service Stations (with or without ancillary services)
                5542,  # Automated Fuel Dispensers
            ],
            "icon": "⛽",
            "display_order": 5,
        },
        {
            "name": "Entertainment & Recreation",
            "category_type": "ENTERTAINMENT",
            "description": "Rewards on movies, concerts, sports events, and entertainment",
            "mcc_codes": [
                7832,  # Motion Picture Theaters
                7929,  # Bands, Orchestras, Entertainment
                7941,  # Sports Clubs, Athletic Fields
                7991,  # Tourist Attractions, Museums
                7996,  # Amusement Parks, Circuses
            ],
            "icon": "🎬",
            "display_order": 6,
        },
        {
            "name": "Grocery & Supermarket",
            "category_type": "GROCERY",
            "description": "Benefits on grocery shopping and supermarket purchases",
            "mcc_codes": [
                5411,  # Grocery Stores, Supermarkets
                5422,  # Meat Provisioners - Freezer and Locker
                5441,  # Candy, Nut, and Confectionery Stores
            ],
            "icon": "🛒",
            "display_order": 7,
        },
        {
            "name": "Online Shopping",
            "category_type": "ONLINE",
            "description": "Special rewards for online shopping and e-commerce platforms",
            "mcc_codes": [],  # Generally identified by merchant name, not MCC
            "icon": "💻",
            "display_order": 8,
        },
        {
            "name": "Utilities & Bills",
            "category_type": "UTILITIES",
            "description": "Cashback on utility bills, phone bills, and recurring payments",
            "mcc_codes": [
                4900,  # Utilities - Electric, Gas, Water, Sanitary
                4814,  # Telecommunication Services
                4812,  # Telecommunication Equipment
            ],
            "icon": "💡",
            "display_order": 9,
        },
        {
            "name": "Education & Learning",
            "category_type": "EDUCATION",
            "description": "Benefits on educational expenses, tuition, and learning materials",
            "mcc_codes": [
                8211,  # Elementary and Secondary Schools
                8220,  # Colleges, Universities
                8299,  # Schools and Educational Services
            ],
            "icon": "📚",
            "display_order": 10,
        },
    ]

    for category_data in categories:
        BenefitCategory.objects.create(**category_data)


def reverse_seed(apps, schema_editor):
    """Remove seeded benefit categories."""
    BenefitCategory = apps.get_model("credit_cards", "BenefitCategory")
    BenefitCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0005_benefitcategory_and_more"),
    ]

    operations = [
        migrations.RunPython(create_benefit_categories, reverse_seed),
    ]
