# Generated by Django 5.2.5

from django.db import migrations


def create_benefit_categories(apps, schema_editor):
    """Seed predefined benefit categories with MCC codes."""
    BenefitCategory = apps.get_model("credit_cards", "BenefitCategory")

    categories = [
        {
            "name": "Restaurant & Dining",
            "category_type": "RESTAURANT",
            "description": "Restaurants, cafes, food courts, and dining establishments",
            "mcc_codes": [5812, 5813, 5814],  # Eating Places & Restaurants
            "icon": "🍽️",
            "display_order": 1,
        },
        {
            "name": "Healthcare & Hospital",
            "category_type": "HEALTHCARE",
            "description": "Hospitals, clinics, pharmacies, and medical services",
            "mcc_codes": [8011, 8021, 8031, 8041, 8042, 8043, 8049, 8050, 8062, 8071, 5912],
            "icon": "🏥",
            "display_order": 2,
        },
        {
            "name": "Shopping & Retail",
            "category_type": "SHOPPING",
            "description": "Department stores, retail shops, and general merchandise",
            "mcc_codes": [5311, 5411, 5651, 5691, 5699, 5732, 5734, 5735],
            "icon": "🛍️",
            "display_order": 3,
        },
        {
            "name": "Travel & Transportation",
            "category_type": "TRAVEL",
            "description": "Airlines, hotels, car rentals, and travel agencies",
            "mcc_codes": [3000, 3001, 3002, 3003, 3004, 4511, 7011, 7512, 7513],
            "icon": "✈️",
            "display_order": 4,
        },
        {
            "name": "Fuel & Gas Stations",
            "category_type": "FUEL",
            "description": "Gas stations, fuel pumps, and automotive fuel",
            "mcc_codes": [5541, 5542, 5983],
            "icon": "⛽",
            "display_order": 5,
        },
        {
            "name": "Entertainment & Recreation",
            "category_type": "ENTERTAINMENT",
            "description": "Movies, theaters, concerts, sports events, and recreation",
            "mcc_codes": [7832, 7841, 7922, 7929, 7932, 7933, 7941, 7991, 7992, 7993, 7994, 7996, 7997, 7998, 7999],
            "icon": "🎬",
            "display_order": 6,
        },
        {
            "name": "Grocery & Supermarket",
            "category_type": "GROCERY",
            "description": "Grocery stores, supermarkets, and food markets",
            "mcc_codes": [5411, 5422, 5441, 5451, 5462],
            "icon": "🛒",
            "display_order": 7,
        },
        {
            "name": "Online Shopping",
            "category_type": "ONLINE",
            "description": "E-commerce platforms and online retailers",
            "mcc_codes": [],  # MCC codes vary for online merchants
            "icon": "💻",
            "display_order": 8,
        },
        {
            "name": "Utilities & Bills",
            "category_type": "UTILITIES",
            "description": "Electric, gas, water, telecom, and utility bill payments",
            "mcc_codes": [4814, 4816, 4899, 4900],
            "icon": "💡",
            "display_order": 9,
        },
        {
            "name": "Education & Learning",
            "category_type": "EDUCATION",
            "description": "Schools, colleges, universities, and educational institutions",
            "mcc_codes": [8211, 8220, 8241, 8244, 8249, 8299],
            "icon": "📚",
            "display_order": 10,
        },
    ]

    for category_data in categories:
        BenefitCategory.objects.create(**category_data)


def reverse_seed_benefit_categories(apps, schema_editor):
    """Remove seeded benefit categories."""
    BenefitCategory = apps.get_model("credit_cards", "BenefitCategory")
    BenefitCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0005_add_ratings_reviews_and_improvements"),
    ]

    operations = [
        migrations.RunPython(create_benefit_categories, reverse_seed_benefit_categories),
    ]
