# Generated by Django 5.2.5 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0010_add_sync_timestamps_to_crawled_content"),
        ("credit_cards", "0006_seed_benefit_categories"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="benefitcategory",
            index=models.Index(
                fields=["is_active", "display_order"], name="idx_category_active_order"
            ),
        ),
        migrations.AddIndex(
            model_name="benefitcategory",
            index=models.Index(fields=["category_type"], name="idx_category_type"),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["is_active", "annual_fee"], name="idx_card_active_fee"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(
                fields=["annual_fee_waiver_difficulty"], name="idx_card_waiver_diff"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(fields=["spending_tier"], name="idx_card_tier"),
        ),
        migrations.AddIndex(
            model_name="creditcard",
            index=models.Index(fields=["bank", "is_active"], name="idx_card_bank_active"),
        ),
        migrations.AddIndex(
            model_name="creditcardbenefit",
            index=models.Index(
                fields=["is_primary", "reward_rate"], name="idx_benefit_primary_rate"
            ),
        ),
        migrations.AddIndex(
            model_name="creditcardbenefit",
            index=models.Index(
                fields=["benefit_category", "is_primary"], name="idx_benefit_cat_primary"
            ),
        ),
    ]
