# Generated by Django 5.2.5 on 2025-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0007_benefitcategory_idx_category_active_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="affiliate_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Affiliate tracking code or partner ID",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="apply_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct application URL (may be affiliate link)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="commission_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed commission amount in BDT per approved application",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated commission rate percentage (e.g., 5.00 for 5%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
