# Generated by Django 5.2.2 on 2025-06-09 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "logo",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=512,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "banks_bank",
                "ordering": ["name"],
            },
        ),
    ]
