# Generated by Django 5.2.2 on 2025-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="bank",
            old_name="updated_at",
            new_name="modified",
        ),
        migrations.AddField(
            model_name="bank",
            name="card_info_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
