# Generated by Django 5.2.3 on 2025-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0003_remove_bank_card_info_urls_bankdatasource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawledcontent",
            name="parsed_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
