# Generated by Django 5.2.4 on 2025-07-29 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0004_make_parsed_json_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="schedule_charge_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL where schedule of charges/fee documents can be found",
                max_length=1024,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
