# Generated by Django 5.2.4 on 2025-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0005_bank_schedule_charge_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankdatasource",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
