# Generated by Django 5.2.4 on 2025-07-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0006_bankdatasource_last_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledcontent",
            name="content_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of extracted content for change detection",
                max_length=64,
            ),
        ),
    ]
