# Generated by Django 5.2.4 on 2025-08-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0007_crawledcontent_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledcontent",
            name="parsed_json_raw",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw extracted data with all fields including non-standard ones",
                null=True,
            ),
        ),
    ]
