# Generated by Django 5.2.4 on 2025-08-07 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0008_crawledcontent_parsed_json_raw"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crawledcontent",
            options={"ordering": ["-crawled_at"]},
        ),
        migrations.RenameField(
            model_name="crawledcontent",
            old_name="crawl_date",
            new_name="crawled_at",
        ),
    ]
