# Generated by Django 5.2.4 on 2025-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0009_alter_crawledcontent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledcontent",
            name="sync_timestamps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of timestamps when this content was re-crawled and found unchanged",
            ),
        ),
    ]
